project:
  type: website
  # output-dir: docs #important step for github pages as per https://www.youtube.com/watch?v=wZ9pZOFSCko

website:
  title: "_brand.yml Demo"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Intranet"
        href: https://intranet.newcastle-hospitals.nhs.uk/
      - text: "NUTH"
        href: https://www.newcastle-hospitals.nhs.uk/
      - text: "Newcastle laboratories"
        href: https://www.newcastlelaboratories.com/
      - text: "HEENE"
        href: https://madeinheene.hee.nhs.uk/medical_microbiology
    tools:
      - icon: github
        href: https://github.com/send2dan/

format:
  html:
    toc: true
    theme:
      - brand

# Use the brand file for all documents in the project
brand: _brand.yml